'use client';
import React, { useEffect, useRef } from 'react';

export default function AnimatedCanvasBackground() {
  const canvasRef = useRef();

    useEffect(() => {
        const canvas = canvasRef.current;
            const ctx = canvas.getContext('2d');
                let raf;
                    let width, height;
                        const orbs = [];
                            const lines = [];

                                function resize(){
                                      width = canvas.width = window.innerWidth;
                                            height = canvas.height = window.innerHeight;
                                                  // generate orbs
                                                        orbs.length = 0;
                                                              for(let i=0;i<6;i++){
                                                                      orbs.push({
                                                                                x: Math.random()*width,
                                                                                          y: Math.random()*height,
                                                                                                    r: 8 + Math.random()*20,
                                                                                                              dx: (Math.random()-0.5)*0.3,
                                                                                                                        dy: (Math.random()-0.5)*0.3,
                                                                                                                                  hue: 45 + Math.random()*40
                                                                                                                                          });
                                                                                                                                                }
                                                                                                                                                      // lines
                                                                                                                                                            lines.length = 0;
                                                                                                                                                                  for(let i=0;i<14;i++){
                                                                                                                                                                          lines.push({ x: Math.random()*width*1.5 - width*0.25, y: (i/14)*height, speed: 0.15 + Math.random()*0.5, angle: Math.random()*Math.PI*2 });
                                                                                                                                                                                }
                                                                                                                                                                                    }

                                                                                                                                                                                        function draw(t){
                                                                                                                                                                                              ctx.clearRect(0,0,width,height);
                                                                                                                                                                                                    // faint grid overlay
                                                                                                                                                                                                          ctx.save();
                                                                                                                                                                                                                ctx.globalAlpha = 0.08;
                                                                                                                                                                                                                      ctx.fillStyle = '#000';
                                                                                                                                                                                                                            ctx.fillRect(0,0,width,height);
                                                                                                                                                                                                                                  ctx.restore();

                                                                                                                                                                                                                                        // moving lines
                                                                                                                                                                                                                                              lines.forEach((L, idx) => {
                                                                                                                                                                                                                                                      ctx.save();
                                                                                                                                                                                                                                                              ctx.translate(0,0);
                                                                                                                                                                                                                                                                      ctx.globalAlpha = 0.06;
                                                                                                                                                                                                                                                                              ctx.beginPath();
                                                                                                                                                                                                                                                                                      ctx.moveTo(-200, (L.y + Math.sin(t/2000 + idx)*40));
                                                                                                                                                                                                                                                                                              ctx.lineTo(width+200, (L.y + Math.sin(t/2000 + idx)*40));
                                                                                                                                                                                                                                                                                                      ctx.strokeStyle = 'rgba(180,160,255,0.12)';
                                                                                                                                                                                                                                                                                                              ctx.lineWidth = 1;
                                                                                                                                                                                                                                                                                                                      ctx.stroke();
                                                                                                                                                                                                                                                                                                                              ctx.restore();
                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                          // orbs
                                                                                                                                                                                                                                                                                                                                                orbs.forEach(o => {
                                                                                                                                                                                                                                                                                                                                                        o.x += o.dx;
                                                                                                                                                                                                                                                                                                                                                                o.y += o.dy;
                                                                                                                                                                                                                                                                                                                                                                        if(o.x < -100) o.x = width + 100;
                                                                                                                                                                                                                                                                                                                                                                                if(o.x > width + 100) o.x = -100;
                                                                                                                                                                                                                                                                                                                                                                                        if(o.y < -100) o.y = height + 100;
                                                                                                                                                                                                                                                                                                                                                                                                if(o.y > height + 100) o.y = -100;

                                                                                                                                                                                                                                                                                                                                                                                                        // glow
                                                                                                                                                                                                                                                                                                                                                                                                                const grad = ctx.createRadialGradient(o.x, o.y, 0, o.x, o.y, o.r*4);
                                                                                                                                                                                                                                                                                                                                                                                                                        grad.addColorStop(0, `rgba(214,184,91,0.9)`);
                                                                                                                                                                                                                                                                                                                                                                                                                                grad.addColorStop(0.25, `rgba(214,184,91,0.35)`);
                                                                                                                                                                                                                                                                                                                                                                                                                                        grad.addColorStop(1, `rgba(214,184,91,0)`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.globalCompositeOperation = 'lighter';
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.fillStyle = grad;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.arc(o.x, o.y, o.r*4, 0, Math.PI*2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ctx.fill();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ctx.globalCompositeOperation = 'source-over';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raf = requestAnimationFrame(draw);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resize();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                window.addEventListener('resize', resize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raf = requestAnimationFrame(draw);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.removeEventListener('resize', resize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cancelAnimationFrame(raf);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return <canvas ref={canvasRef} style={{ position:'fixed', inset:0, zIndex:0, pointerEvents:'none' }} />;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            