// zeiroko-next-firebase/components/AuthFirstPage.jsx

'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { auth } from '../lib/firebaseClient';
import { 
    GoogleAuthProvider, 
        TwitterAuthProvider, 
            signInWithPopup,
                createUserWithEmailAndPassword,
                    signInWithEmailAndPassword 
                    } from 'firebase/auth';

                    export default function AuthFirstPage() {
                        const router = useRouter();
                            const [isLogin, setIsLogin] = useState(true);
                                const [email, setEmail] = useState('');
                                    const [password, setPassword] = useState('');
                                        const [error, setError] = useState(null);

                                            // Redirect if already logged in (simple check)
                                                useEffect(() => {
                                                        const unsubscribe = auth.onAuthStateChanged(user => {
                                                                    if (user) {
                                                                                    user.getIdToken().then(token => {
                                                                                                        localStorage.setItem('ZE_ID_TOKEN', token);
                                                                                                                            // Redirect to the role selection page
                                                                                                                                                router.push('/role-select'); 
                                                                                                                                                                });
                                                                                                                                                                            }
                                                                                                                                                                                    });
                                                                                                                                                                                            return () => unsubscribe();
                                                                                                                                                                                                }, [router]);

                                                                                                                                                                                                    // Helper to handle token storage and redirect after successful auth
                                                                                                                                                                                                        const handleAuthSuccess = async (userCredential) => {
                                                                                                                                                                                                                const user = userCredential.user;
                                                                                                                                                                                                                        const token = await user.getIdToken();
                                                                                                                                                                                                                                localStorage.setItem('ZE_ID_TOKEN', token);
                                                                                                                                                                                                                                        // The /role-select page (or /home) is the next step after the first auth
                                                                                                                                                                                                                                                router.push('/role-select'); 
                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                        // --- Social Providers ---
                                                                                                                                                                                                                                                            const signInWithSocial = async (provider) => {
                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                const providerInstance = provider === 'google' ? new GoogleAuthProvider() : new TwitterAuthProvider();
                                                                                                                                                                                                                                                                                            const result = await signInWithPopup(auth, providerInstance);
                                                                                                                                                                                                                                                                                                        handleAuthSuccess(result);
                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                            setError(err.message);
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                            // --- Email/Password Auth ---
                                                                                                                                                                                                                                                                                                                                                const handleEmailAuth = async (e) => {
                                                                                                                                                                                                                                                                                                                                                        e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                setError(null);
                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                    let result;
                                                                                                                                                                                                                                                                                                                                                                                                if (isLogin) {
                                                                                                                                                                                                                                                                                                                                                                                                                result = await signInWithEmailAndPassword(auth, email, password);
                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                            result = await createUserWithEmailAndPassword(auth, email, password);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    handleAuthSuccess(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setError(err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="auth-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h1 className="title">ZEIROKO</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2>{isLogin ? 'Connect or Log In' : 'Sign Up'}</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error && <p className="error-message">{error}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="social-login-buttons">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="social-btn google-btn glow-effect" onClick={() => signInWithSocial('google')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Connect with Google
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="social-btn twitter-btn glow-effect" onClick={() => signInWithSocial('twitter')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Connect with Twitter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="separator">OR</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <form onSubmit={handleEmailAuth}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" className="primary-btn">{isLogin ? 'Log In' : 'Sign Up'}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="switch-auth">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isLogin ? "Don't have an account?" : "Already have an account?"} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="#" onClick={(e) => { e.preventDefault(); setIsLogin(!isLogin); }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {isLogin ? 'Sign Up' : 'Log In'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        